version: "3"
services:

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    links:
      - fpm
      - mysql
    volumes:
      - ./:/var/www/laravel
      - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/laravel.conf
    working_dir: /var/www/laravel

  fpm:
    build: ./docker/php-fpm
    volumes:
      - ./:/var/www/laravel
    working_dir: /var/www/laravel

  mysql:
    image: mysql:5.7.29
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./.data:/var/lib/mysql
    ports:
      - 3306:3306

  redis:
    image: redis
    command: redis-server --requirepass root!
    ports:
      - "6379:6379"
